### ISSUE TITLE
Typescript file doesn't compile

### ISSUE THREAD

**Issue by mattbishop** [sindresorhus/open#136]
I'm using 6.3.0's provided typescript definition file but it does not compile with TS 3.2.2:

```
yarn build                                                                                                                                   5.9s  Mon 20 May 14:31:39 2019
yarn run v1.15.2
$ tsc
../node_modules/open/index.d.ts:33:36 - error TS1005: ';' expected.

33  	readonly app?: string | readonly string[];
    	                                 ~~~~~~

../node_modules/open/index.d.ts:33:43 - error TS1011: An element access expression should take an argument.

33  	readonly app?: string | readonly string[];


../node_modules/open/index.d.ts:35:1 - error TS1128: Declaration or statement expected.

35 }```

I think the second `readonly` on line 33 can be omitted, especially given `app` itself is marked as `.

**Comment by sindresorhus** [comment]
Duplicate of #130
